version: "3.9"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_DATABASE: elecampaign
      MYSQL_ROOT_PASSWORD: RAVIkumar@9866

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  campaign-api:
    image: java-app:latest     # THIS IS IMPORTANT
    container_name: campaign-api
    restart: always

    ports:
      - "8081:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/elecampaign?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: campaign_user
      SPRING_DATASOURCE_PASSWORD: campaign@123

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_MAIN_LAZY_INITIALIZATION: "true"
      SERVER_PORT: 8080

    depends_on:
      mysql-db:
        condition: service_healthy

volumes:
  mysql_data: