#spring.application.name=campaign

server.port=8090
#spring.main.banner-mode=on


# MySQL Data Source Configuration
# AFTER (The Fix)
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/campaign?allowPublicKeyRetrieval=true&useSSL=false
#  jdbc:mysql://13.235.244.103:3306/elecampaign?useSSL=false&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=root@123
#  RAVIkumar@9866

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA and Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true


# spring.jpa.open-in-view=false



otp.msg91.auth-key=7e8d3c1fXXXXXXXXXXXXXXXX
otp.msg91.sender-id=CMPAGN
otp.msg91.template-id=1707168976543210987

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html


aws.region=ap-south-1
aws.sns.sender-id=CAMPAIGN


#MSG_HOST_NAME=control.msg91.com
#MSG_PATH_URL=/api/v5/flow
#MSG91_AUTH_KEY=436990AVoO3UjCn676a4df5P1
#LOGIN_CAMPAIGn=6980cfd1d5da6b035c3d2c83


msg91.host=control.msg91.com
msg91.path=/api/v5/flow
msg91.auth-key=YOUR_MSG91_AUTH_KEY
msg91.login-campaign=YOUR_FLOW_ID